#!/bin/sh
#cgi script das die qss led an- bzw. ausschaltet
#ip/cgi-bin/dmx?value=100&channel=1     setzt channel 1 auf Valse 100


#den value aus den get parametern auslesen
VALUE=`echo "$QUERY_STRING" | grep -oE "(^|[?&])value=[^&]+" |  sed "s/%20/ /g" | cut -f 2 -d "=" | head -n1`
CHANNEL=`echo "$QUERY_STRING" | grep -oE "(^|[?&])channel=[^&]+" |  sed "s/%20/ /g" | cut -f 2 -d "="`

#ausgabe der eingegebenen parameter
echo value: $VALUE
echo channel: $CHANNEL

echo 'oy'$CHANNEL'c'$VALUE'w'


#echo ''$CHANNEL'c'$VALUE'w' | nc localhost 2001 ;
echo 'oy'$CHANNEL'c'$VALUE'w' > /dev/ttyS0
